
# Add labels from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - Structured illumination reconstruction
  - Super-resolution microscopy
  - 3D image
  - Spatial properties
  - Image processing
  - Frequency-domain transformation
  - Image convolution
